import numpy as np
arr = np.array([13242424343])
print(arr)


import numpy as np
arange = np.arange(1, 100, 10)
print(arange)

import numpy as np
filled_array = np.full((4,7),99)
print(filled_array)


import numpy as np
identity_matrix = np.eye(99)
print(identity_matrix)

import numpy as np
zeros_array = np.zeros(300)
                   
print(zeros_array)

import numpy as np
arr = np.array("8.99")
print(arr.dtype)
print(arr)


import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)